import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';
const URL='https://gbtmdwknkepuqbsefhto.supabase.co';
const KEY=localStorage.getItem('gvbs_supabase_key')||prompt('Вставь publishable key Supabase');
if(KEY) localStorage.setItem('gvbs_supabase_key',KEY);
const db=createClient(URL,KEY||'');
const T='media_chat_messages',B='media-chat',P='gvbs-pages-profile',R='gvbs-regulation-url';
const $=s=>document.querySelector(s),app=$('#app');
const j=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
let state={profile:j(P,null),msgs:[],files:[],audio:null,rec:null,chunks:[],tab:'chat',regulationUrl:localStorage.getItem(R)||''};
const esc=t=>{const d=document.createElement('div');d.textContent=t??'';return d.innerHTML};
const tm=v=>new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const avatar=(name,url)=>url?`<img class='avatar-img' src='${url}' alt='avatar'>`:`<span class='avatar-fallback'>${esc((name||'U').slice(0,1).toUpperCase())}</span>`;
const save=()=>localStorage.setItem(P,JSON.stringify(state.profile));
const saveReg=()=>localStorage.setItem(R,state.regulationUrl||'');
function login(){app.innerHTML=`<div class='shell login-wrap'><div class='card'><div class='pill'>GVBS MEDIA CHAT</div><h1>Открыть чат</h1><p>Введи имя и, если хочешь, сразу добавь аватарку.</p><input class='input' id='n' placeholder='Например: Сергей монтаж'><input id='a' type='file' accept='image/*' class='hidden'><button class='ghost full' id='ap'>Загрузить аватар</button><div class='avatar-upload' id='avp'></div><button class='primary' id='go'>Войти</button></div></div>`; let avatarUrl=''; $('#ap').onclick=()=>$('#a').click(); $('#a').onchange=async()=>{const f=$('#a').files[0]; if(!f)return; avatarUrl=await fileToDataUrl(f); $('#avp').innerHTML=`<div class='profile-line'><div class='avatar big'>${avatar('',avatarUrl)}</div><span>Аватар загружен</span></div>`;}; $('#go').onclick=()=>{const n=$('#n').value.trim(); if(!n)return; state.profile={id:crypto.randomUUID(),name:n,avatar:avatarUrl}; save(); boot();};}
function shell(){const p=state.profile; app.innerHTML=`<div class='shell'><div class='layout'><aside class='sidebar'><div class='pill'>MEDIA ROOM</div><h2>Медиа-служение</h2><p>Общая история на всех устройствах через Supabase.</p><div class='section'><div class='section-title'>Профиль</div><div class='profile-line'><div class='avatar'>${avatar(p.name,p.avatar)}</div><div><div class='name-strong'>${esc(p.name)}</div><div class='muted' id='st'>Подключение...</div></div></div></div><div class='section'><div class='section-title'>Навигация</div><button class='nav-btn ${state.tab==='chat'?'active':''}' id='tabChat'>Чат</button><button class='nav-btn ${state.tab==='rules'?'active':''}' id='tabRules'>Регламент</button></div></aside><main class='chat'><header class='chat-head'><div><h1>${state.tab==='chat'?'Чат медиа-служения':'Регламент медиа-служения'}</h1><p>${state.tab==='chat'?'Сообщения, фото и голосовые':'PDF и базовые материалы команды'}</p></div><div class='head-actions'><button class='profile-chip' id='rename'><div class='avatar small'>${avatar(p.name,p.avatar)}</div><span>${esc(p.name)}</span></button></div></header><section class='tab ${state.tab==='chat'?'':'hidden'}' id='chatTab'><div class='messages' id='m'></div><button class='jump hidden' id='down' aria-label='Вниз'>↓</button><div class='composer'><div class='tool-row'><input id='f' type='file' accept='image/*' multiple class='hidden'><button class='icon-btn' id='pf' title='Фото'>🖼️</button><button class='icon-btn mic ${state.rec?'recording':''}' id='vr' title='Голосовое'>🎤</button><button class='ghost lock hidden' id='lockVoice'>Закрепить запись</button></div><div class='previews' id='p'></div><div class='composer-row'><textarea id='t' placeholder='Напиши сообщение' rows='1'></textarea><button class='send' id='s'>➤</button></div></div></section><section class='tab ${state.tab==='rules'?'':'hidden'} regulation' id='rulesTab'><div class='rules-card'><div class='section-title'>Ссылка на PDF регламент</div><div class='rules-form'><input class='input' id='regUrl' placeholder='Вставь публичную ссылку на PDF' value='${esc(state.regulationUrl)}'><button class='ghost' id='saveReg'>Сохранить</button></div><p class='muted'>Когда добавишь публичную ссылку на PDF, он откроется здесь же для чтения.</p>${state.regulationUrl?`<iframe class='pdf-frame' src='${state.regulationUrl}'></iframe>`:`<div class='empty-rules'>Пока PDF не подключён</div>`}</div></section></main></div></div>`; bind(); draw();}
function draw(){const c=$('#m'); if(!c)return; c.innerHTML=state.msgs.map(x=>`<div class='message ${x.author_id===state.profile.id?'own':''}'><div class='bubble'><div class='meta'><div class='avatar xsmall'>${avatar(x.author_name,'')}</div><strong>${esc(x.author_name)}</strong><span>${tm(x.created_at)}</span>${x.author_id===state.profile.id&&!x.deleted_at?`<button class='small-btn' data-e='${x.id}'>Изм.</button><button class='small-btn' data-d='${x.id}'>Удал.</button>`:''}</div>${x.deleted_at?`<div class='deleted'>Сообщение удалено</div>`:`<div class='text'>${esc(x.text||'')}</div>`}${(x.attachments||[]).length?`<div class='media-grid'>${x.attachments.map(a=>a.kind==='audio'?`<audio controls src='${a.url}'></audio>`:`<img src='${a.url}' alt='${esc(a.name||'media')}'>`).join('')}</div>`:''}</div></div>`).join(''); c.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>db.from(T).update({text:'',deleted_at:new Date().toISOString()}).eq('id',b.dataset.d)); c.querySelectorAll('[data-e]').forEach(b=>b.onclick=async()=>{const row=state.msgs.find(x=>x.id===b.dataset.e); if(!row)return; const next=prompt('Редактировать сообщение',row.text||''); if(next==null)return; await db.from(T).update({text:next}).eq('id',row.id);}); setTimeout(()=>c.scrollTo({top:c.scrollHeight,behavior:'smooth'}),40);}
function previews(){const p=$('#p'); if(!p)return; p.innerHTML=[...state.files.map(f=>`<span class='preview-chip'>${esc(f.name)}</span>`), state.audio?`<span class='preview-chip danger-chip'>Голосовое готово</span>`:''].filter(Boolean).join('');}
function grow(){const t=$('#t'); if(!t)return; t.style.height='0px'; t.style.height=Math.min(t.scrollHeight,170)+'px';}
async function fileToDataUrl(file){return new Promise(r=>{const fr=new FileReader(); fr.onload=()=>r(fr.result); fr.readAsDataURL(file);});}
async function up(){const out=[]; for(const f of state.files){const path=`${Date.now()}-${crypto.randomUUID()}-${f.name}`; const r=await db.storage.from(B).upload(path,f,{upsert:false,cacheControl:'3600'}); if(r.error) throw r.error; out.push({kind:'image',name:f.name,url:db.storage.from(B).getPublicUrl(path).data.publicUrl});} if(state.audio){const f=new File([state.audio],`voice-${Date.now()}.webm`,{type:state.audio.type||'audio/webm'}); const path=`${Date.now()}-${crypto.randomUUID()}-${f.name}`; const r=await db.storage.from(B).upload(path,f,{upsert:false,cacheControl:'3600'}); if(r.error) throw r.error; out.push({kind:'audio',name:f.name,url:db.storage.from(B).getPublicUrl(path).data.publicUrl});} return out;}
async function send(){const t=$('#t'); const text=t.value.trim(); if(!text&&!state.files.length&&!state.audio) return; try{const attachments=await up(); const r=await db.from(T).insert({author_id:state.profile.id,author_name:state.profile.name,text,attachments}); if(r.error) throw r.error; state.files=[]; state.audio=null; t.value=''; grow(); previews();}catch(e){alert('Проверь SQL-настройку Supabase и bucket media-chat'); console.error(e);}}
async function load(){const r=await db.from(T).select('*').order('created_at',{ascending:true}); const st=$('#st'); if(r.error){if(st) st.textContent='Нужно проверить SQL / Realtime'; console.error(r.error); return;} if(st) st.textContent='Подключено к общей базе'; state.msgs=r.data||[]; draw();}
function sub(){db.channel('media-chat-room').on('postgres_changes',{event:'*',schema:'public',table:T},()=>load()).subscribe();}
async function rec(btn){if(state.rec){state.rec.stop(); state.rec=null; btn.classList.remove('recording'); btn.textContent='🎤'; $('#lockVoice')?.classList.add('hidden'); return;} const stream=await navigator.mediaDevices.getUserMedia({audio:true}); state.chunks=[]; const r=new MediaRecorder(stream); r.ondataavailable=e=>state.chunks.push(e.data); r.onstop=()=>{state.audio=new Blob(state.chunks,{type:'audio/webm'}); stream.getTracks().forEach(t=>t.stop()); previews();}; r.start(); state.rec=r; btn.classList.add('recording'); btn.textContent='⏺'; $('#lockVoice')?.classList.remove('hidden');}
function bind(){ $('#tabChat').onclick=()=>{state.tab='chat'; shell(); sub(); load();}; $('#tabRules').onclick=()=>{state.tab='rules'; shell(); sub();}; $('#rename').onclick=async()=>{const n=prompt('Новое имя участника',state.profile.name||''); if(!n||!n.trim()) return; state.profile.name=n.trim(); const change=confirm('Обновить аватар?'); if(change){const inp=document.createElement('input'); inp.type='file'; inp.accept='image/*'; inp.onchange=async()=>{const f=inp.files?.[0]; if(f){state.profile.avatar=await fileToDataUrl(f); save(); shell(); sub(); load();}}; inp.click();} save(); shell(); sub(); load();}; $('#pf')?.addEventListener('click',()=>$('#f').click()); $('#f')?.addEventListener('change',()=>{state.files=[...$('#f').files]; previews();}); $('#vr')?.addEventListener('click',e=>rec(e.target)); $('#lockVoice')?.addEventListener('click',()=>{if(state.rec){state.rec.stop(); state.rec=null; $('#vr').classList.remove('recording'); $('#vr').textContent='🎤'; $('#lockVoice').classList.add('hidden');}}); $('#s')?.addEventListener('click',send); $('#t')?.addEventListener('input',grow); $('#t')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}); $('#down')?.addEventListener('click',()=>$('#m').scrollTo({top:$('#m').scrollHeight,behavior:'smooth'})); $('#m')?.addEventListener('scroll',()=>$('#down').classList.toggle('hidden',$('#m').scrollHeight-$('#m').scrollTop-$('#m').clientHeight<=180)); $('#saveReg')?.addEventListener('click',()=>{state.regulationUrl=$('#regUrl').value.trim(); saveReg(); shell(); sub(); if(state.tab==='chat') load();}); grow();}
function boot(){shell(); sub(); load();}
state.profile?boot():login();
