import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';
const URL='https://gbtmdwknkepuqbsefhto.supabase.co';
const KEY=localStorage.getItem('gvbs_supabase_key')||prompt('Вставь publishable key Supabase один раз для этого браузера');
if(KEY) localStorage.setItem('gvbs_supabase_key',KEY);
const db=createClient(URL,KEY||'');
const T='media_chat_messages',B='media-chat',P='gvbs-pages-profile';
const $=s=>document.querySelector(s); const app=$('#app');
let state={profile:JSON.parse(localStorage.getItem(P)||'null'),msgs:[],files:[],audio:null,rec:null,chunks:[]};
const esc=t=>{const d=document.createElement('div');d.textContent=t??'';return d.innerHTML};
const tm=v=>new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const save=()=>localStorage.setItem(P,JSON.stringify(state.profile));
function login(){app.innerHTML=`<div class='shell login-wrap'><div class='card'><div class='pill'>GVBS MEDIA CHAT</div><h1>Общий чат</h1><p>После SQL-настройки в Supabase сообщения будут видны всем устройствам.</p><input class='input' id='n' placeholder='Например: Сергей монтаж'><button class='primary' id='go'>Войти</button><div class='note'>Нужен файл supabase-setup.sql из репозитория.</div></div></div>`;$('#go').onclick=()=>{const n=$('#n').value.trim(); if(!n)return; state.profile={id:crypto.randomUUID(),name:n}; save(); boot();};}
function shell(){app.innerHTML=`<div class='shell'><div class='layout'><aside class='sidebar'><div class='pill'>MEDIA ROOM</div><h2>Медиа-служение</h2><p>Общая история на всех устройствах через Supabase.</p><div class='section'><div class='section-title'>Профиль</div><div class='online-item'><span class='dot'></span>${esc(state.profile.name)}</div></div><div class='section'><div class='section-title'>Статус</div><p id='st'>Подключение...</p></div></aside><main class='chat'><header class='chat-head'><div><h1>Чат медиа-служения</h1><p>Supabase shared chat</p></div><div class='head-actions'><button class='ghost' id='downTop'>Вниз</button><button class='ghost' id='rename'>Имя</button></div></header><div class='messages' id='m'></div><div class='typing'></div><button class='jump hidden' id='down'>↓</button><div class='composer'><div class='tool-row'><input id='f' type='file' accept='image/*,image/gif' multiple class='hidden'><button class='ghost' id='pf'>Фото / GIF</button><button class='ghost' id='vr'>Голосовое</button><button class='danger' id='clr'>Скрыть системное</button></div><div class='previews' id='p'></div><div class='composer-row'><textarea id='t' placeholder='Напиши сообщение' rows='1'></textarea><button class='send' id='s'>Отправить</button></div></div></main></div></div>`; bind(); draw();}
function draw(){const c=$('#m'); if(!c)return; c.innerHTML=state.msgs.map(x=>`<div class='message ${x.author_id===state.profile.id?'own':''}'><div class='bubble'><div class='meta'><strong>${esc(x.author_name)}</strong><span>${tm(x.created_at)}</span>${x.author_id===state.profile.id&&!x.deleted_at?`<button class='small-btn' data-d='${x.id}'>Удалить</button>`:''}</div>${x.deleted_at?`<div class='deleted'>Сообщение удалено</div>`:`<div class='text'>${esc(x.text||'')}</div>`}${(x.attachments||[]).length?`<div class='media-grid'>${x.attachments.map(a=>a.kind==='audio'?`<audio controls src='${a.url}'></audio>`:`<img src='${a.url}' alt='${esc(a.name||'media')}'>`).join('')}</div>`:''}</div></div>`).join(''); c.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>db.from(T).update({text:'',deleted_at:new Date().toISOString()}).eq('id',b.dataset.d)); setTimeout(()=>c.scrollTo({top:c.scrollHeight,behavior:'smooth'}),50);}
function previews(){const p=$('#p'); if(!p)return; p.innerHTML=[...state.files.map(f=>`<span class='preview-chip'>${esc(f.name)}</span>`), state.audio?`<span class='preview-chip'>Голосовое готово</span>`:''].filter(Boolean).join('');}
function grow(){const t=$('#t'); if(!t)return; t.style.height='0px'; t.style.height=Math.min(t.scrollHeight,190)+'px';}
async function up(){const out=[]; for(const f of state.files){const path=`${Date.now()}-${crypto.randomUUID()}-${f.name}`; let r=await db.storage.from(B).upload(path,f,{upsert:false,cacheControl:'3600'}); if(r.error) throw r.error; let pub=db.storage.from(B).getPublicUrl(path).data.publicUrl; out.push({kind:f.type==='image/gif'?'gif':'image',name:f.name,url:pub});} if(state.audio){const f=new File([state.audio],`voice-${Date.now()}.webm`,{type:state.audio.type||'audio/webm'}); const path=`${Date.now()}-${crypto.randomUUID()}-${f.name}`; let r=await db.storage.from(B).upload(path,f,{upsert:false,cacheControl:'3600'}); if(r.error) throw r.error; let pub=db.storage.from(B).getPublicUrl(path).data.publicUrl; out.push({kind:'audio',name:f.name,url:pub});} return out;}
async function send(){const t=$('#t'); const text=t.value.trim(); if(!text&&!state.files.length&&!state.audio) return; try{const attachments=await up(); const r=await db.from(T).insert({author_id:state.profile.id,author_name:state.profile.name,text,attachments}); if(r.error) throw r.error; state.files=[]; state.audio=null; t.value=''; grow(); previews();}catch(e){alert('Нужно выполнить SQL из supabase-setup.sql и создать bucket media-chat.'); console.error(e);}}
async function load(){const r=await db.from(T).select('*').order('created_at',{ascending:true}); if(r.error){$('#st').textContent='Нужно выполнить SQL-настройку в Supabase'; console.error(r.error); return;} $('#st').textContent='Подключено к общей базе'; state.msgs=r.data||[]; draw();}
function sub(){db.channel('media-chat-room').on('postgres_changes',{event:'*',schema:'public',table:T},()=>load()).subscribe();}
async function rec(btn){if(state.rec){state.rec.stop(); state.rec=null; btn.textContent='Голосовое'; return;} const stream=await navigator.mediaDevices.getUserMedia({audio:true}); state.chunks=[]; const r=new MediaRecorder(stream); r.ondataavailable=e=>state.chunks.push(e.data); r.onstop=()=>{state.audio=new Blob(state.chunks,{type:'audio/webm'}); stream.getTracks().forEach(t=>t.stop()); previews();}; r.start(); state.rec=r; btn.textContent='Стоп запись';}
function bind(){$('#t').addEventListener('input',grow); $('#t').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}); $('#pf').onclick=()=>$('#f').click(); $('#f').onchange=()=>{state.files=[...$('#f').files]; previews();}; $('#vr').onclick=e=>rec(e.target); $('#s').onclick=send; $('#clr').onclick=()=>{state.msgs=state.msgs.filter(x=>x.author_id!=='system'); draw();}; $('#down').onclick=()=>$('#m').scrollTo({top:$('#m').scrollHeight,behavior:'smooth'}); $('#downTop').onclick=()=>$('#m').scrollTo({top:$('#m').scrollHeight,behavior:'smooth'}); $('#rename').onclick=()=>{const n=prompt('Новое имя участника',state.profile.name||''); if(!n||!n.trim()) return; state.profile.name=n.trim(); save(); shell(); sub(); load();}; $('#m').addEventListener('scroll',()=>$('#down').classList.toggle('hidden',$('#m').scrollHeight-$('#m').scrollTop-$('#m').clientHeight<=180)); grow();}
function boot(){shell(); sub(); load();}
state.profile?boot():login();
