(function(){
var SUPABASE_URL='https://gbtmdwknkepuqbsefhto.supabase.co';
var SUPABASE_KEY='sb_publishable_4BB1LRShAX8uRQXACVN5rg_CaPtiiHz';
var BACKEND_URL='https://max-church-chat-starter-supabase.onrender.com';
var TABLE='media_chat_messages';
var BUCKET='media-chat';
var ACCESS='MEDIA2026';
var PROFILE='gvbs-v2-profile';
var NOTIFY='gvbs-notify-enabled';
var EMOJIS=['😀','😂','😊','😍','🙏','🙌','👏','❤️','💙','🔥','👍','👎','👀','🎬','📸','🎤','✨'];
var REACTIONS=['👍','👎','❤️','🙏','🔥','👀'];
var ROLES=['Руководитель','Координатор','Оператор','Фотограф','Монтажёр','Звук','Свет','Дизайн','Публикатор','Участник'];
var app=document.getElementById('app');
var db=null;
var state={profile:read(PROFILE,null),tab:'chat',messages:[],files:[],audio:null,rec:null,chunks:[],emoji:false,reactions:read('gvbs-v2-reactions',{})};
function read(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(t){var d=document.createElement('div');d.textContent=t||'';return d.innerHTML}
function av(p){return p&&p.avatar?"<img src='"+p.avatar+"'>":esc(((p&&p.name)||'U').slice(0,1).toUpperCase())}
function tm(v){try{return new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){return''}}
function alertErr(e){console.error(e);app.innerHTML="<div class='login'><div class='login-card'><div class='eyebrow'>GVBS MEDIA HUB</div><h1>Не удалось открыть приложение</h1><p class='muted'>Ошибка загрузки. Обнови страницу или открой в инкогнито.</p><button class='primary' onclick='location.reload()'>Обновить</button><pre class='note'>"+esc(e&&e.message?e.message:String(e))+"</pre></div></div>"}
function init(){try{if(!window.supabase||!window.supabase.createClient)throw new Error('Supabase SDK не загрузился');db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);state.profile?boot():login()}catch(e){alertErr(e)}}
function login(){app.innerHTML="<div class='login'><div class='login-card'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>GVBS MEDIA HUB</div><h1>Вход в чат медиаслужения</h1></div></div><p class='muted'>Закрытое пространство команды: чат, регламент, файлы, уведомления и профиль.</p><div class='form'><input class='input' id='name' placeholder='Имя'><select class='input' id='role'>"+ROLES.map(function(r){return'<option>'+r+'</option>'}).join('')+"</select><input class='input' id='code' placeholder='Код доступа'><input id='avatar' class='fileInput' type='file' accept='image/*'><button class='ghost' id='pick'>Загрузить аватар</button><button class='primary' id='enter'>Войти</button><div class='note' id='note'>Код доступа: MEDIA2026</div></div></div></div>";var avatar='';document.getElementById('pick').onclick=function(){document.getElementById('avatar').click()};document.getElementById('avatar').onchange=function(){var f=this.files[0];if(!f)return;var fr=new FileReader();fr.onload=function(){avatar=fr.result;document.getElementById('note').textContent='Аватар загружен'};fr.readAsDataURL(f)};document.getElementById('enter').onclick=function(){var name=document.getElementById('name').value.trim();var role=document.getElementById('role').value;var code=document.getElementById('code').value.trim();if(code!==ACCESS){alert('Неверный код доступа');return}if(!name)return;state.profile={id:crypto.randomUUID(),name:name,role:role,avatar:avatar};save(PROFILE,state.profile);boot()}}
function boot(){shell();load();db.channel('v2-chat').on('postgres_changes',{event:'*',schema:'public',table:TABLE},load).subscribe()}
function shell(){var p=state.profile;app.innerHTML="<div class='app'><div class='layout'><aside class='side'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>MEDIA HUB</div><h1>Медиа-служение</h1></div></div><p class='muted'>Командный чат, файлы, регламент и push-уведомления.</p><div class='profile-mini'><div class='avatar'>"+av(p)+"</div><div><strong>"+esc(p.name)+"</strong><div class='muted'>"+esc(p.role)+"</div></div></div><div class='metric'><div><strong>Статус</strong><br><span class='muted' id='conn'>Подключение...</span></div><div><strong>Push</strong><br><span class='muted'>"+(localStorage.getItem(NOTIFY)==='1'?'включены':'выключены')+"</span></div></div></aside><main class='main'><header class='top'><div><h2>"+title()+"</h2><div class='muted'>"+sub()+"</div></div><button class='profile-btn' id='profileBtn'><div class='avatar sm'>"+av(p)+"</div></button></header><section class='content' id='content'></section><nav class='bottom'>"+nav()+"</nav></main></div></div>";document.getElementById('profileBtn').onclick=function(){state.tab='profile';shell()};Array.prototype.forEach.call(document.querySelectorAll('[data-tab]'),function(b){b.onclick=function(){state.tab=this.dataset.tab;shell()}});draw()}
function title(){return{chat:'GVBS Media Hub',files:'Файлы команды',rules:'Регламент',notify:'Уведомления',profile:'Профиль'}[state.tab]||'GVBS'}
function sub(){return{chat:'Чат медиаслужения · фото · голосовые · реакции',files:'Документы и материалы',rules:'Положение о медиаслужении',notify:'Push и диагностика',profile:'Настройки участника'}[state.tab]||''}
function nav(){return[['chat','💬','Чат'],['files','📁','Файлы'],['rules','📄','Регламент'],['notify','🔔','Push'],['profile','👤','Профиль']].map(function(x){return"<button class='nav "+(state.tab===x[0]?'active':'')+"' data-tab='"+x[0]+"'><b>"+x[1]+"</b><span>"+x[2]+"</span></button>"}).join('')}
function draw(){if(state.tab==='chat')chat();if(state.tab==='files')files();if(state.tab==='rules')rules();if(state.tab==='notify')notify();if(state.tab==='profile')profile()}
function chat(){document.getElementById('content').innerHTML="<div class='chat-screen'><div class='messages' id='msgs'></div><button class='jump hidden' id='jump'>↓</button><div class='composer'><div class='emoji-panel' id='emoji'>"+EMOJIS.map(function(e){return'<button>'+e+'</button>'}).join('')+"</div><div class='preview' id='preview'></div><div class='composer-row'><button class='tool' id='em'>😊</button><textarea class='input' id='txt' maxlength='3000' placeholder='Сообщение'></textarea><input id='photo' class='fileInput' type='file' accept='image/*' multiple><button class='tool' id='clip'>📎</button><button class='send' id='send'>🎤</button></div></div></div>";bindComposer();messages()}
function messages(){var box=document.getElementById('msgs');if(!box)return;box.innerHTML=state.messages.map(function(m){var own=m.author_id===state.profile.id;var react=state.reactions[m.id]||'';return"<div class='msg "+(own?'own':'')+"'><div class='bubble'><div class='meta'><strong>"+esc(m.author_name)+"</strong><span class='role'>"+esc(m.author_role||'Участник')+"</span><span>"+tm(m.created_at)+"</span></div>"+(m.deleted_at?"<div class='deleted'>Сообщение удалено</div>":"<div class='text'>"+esc(m.text||'')+"</div>")+media(m)+"<div class='msg-actions'>"+REACTIONS.map(function(r){return"<button class='react "+(react===r?'active':'')+"' data-id='"+m.id+"' data-r='"+r+"'>"+r+"</button>"}).join('')+"</div></div></div>"}).join('');Array.prototype.forEach.call(box.querySelectorAll('[data-r]'),function(b){b.onclick=function(){state.reactions[b.dataset.id]=state.reactions[b.dataset.id]===b.dataset.r?'':b.dataset.r;save('gvbs-v2-reactions',state.reactions);messages()}});setTimeout(function(){box.scrollTop=box.scrollHeight},30)}
function media(m){var a=m.attachments||[];if(!a.length)return'';return"<div class='media'>"+a.map(function(x){return x.kind==='audio'?"<audio controls src='"+x.url+"'></audio>":"<img src='"+x.url+"'>"}).join('')+"</div>"}
function bindComposer(){var t=document.getElementById('txt'),s=document.getElementById('send');document.getElementById('em').onclick=function(){document.getElementById('emoji').classList.toggle('open')};Array.prototype.forEach.call(document.querySelectorAll('#emoji button'),function(b){b.onclick=function(){t.value+=b.textContent;mode()}});document.getElementById('clip').onclick=function(){document.getElementById('photo').click()};document.getElementById('photo').onchange=function(){state.files=Array.prototype.slice.call(this.files).filter(function(f){return f.type.indexOf('image/')===0&&f.size<=10485760}).slice(0,6);preview();mode()};t.oninput=function(){this.style.height='0px';this.style.height=Math.min(this.scrollHeight,170)+'px';mode()};t.onkeydown=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};s.onclick=function(){t.value.trim()||state.files.length?send():record()};mode()}
function preview(){var p=document.getElementById('preview');if(p)p.innerHTML=state.files.map(function(f){return'<span>'+esc(f.name)+'</span>'}).join('')}
function mode(){var t=document.getElementById('txt'),s=document.getElementById('send');if(s)s.textContent=(t&&t.value.trim())||state.files.length?'➤':'🎤'}
async function upload(){var out=[];for(var i=0;i<state.files.length;i++){var f=state.files[i];var path=Date.now()+'-'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Zа-яА-Я0-9._-]/g,'_');var r=await db.storage.from(BUCKET).upload(path,f,{upsert:false});if(r.error)throw r.error;out.push({kind:'image',name:f.name,url:db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl})}return out}
async function send(){var t=document.getElementById('txt');var text=t.value.trim();if(!text&&!state.files.length)return;try{var attachments=await upload();var r=await db.from(TABLE).insert({author_id:state.profile.id,author_name:state.profile.name,author_role:state.profile.role,text:text,attachments:attachments});if(r.error)throw r.error;state.files=[];t.value='';preview();mode()}catch(e){alert(e.message||'Ошибка отправки')}}
function record(){alert('Голосовые будут включены следующим патчем. Текст и фото уже работают.')} 
function files(){document.getElementById('content').innerHTML="<section class='screen'><div class='grid'><div class='card'><div class='eyebrow'>ФАЙЛЫ</div><h2>Материалы команды</h2><p class='muted'>Регламенты, чек-листы, шаблоны и ссылки.</p></div><div class='card'><strong>Положение о медиаслужении</strong><p class='muted'>PDF · рабочая версия</p><button class='primary' onclick='window.gvbsDownloadReg&&window.gvbsDownloadReg()'>Скачать PDF</button></div></div></section>"}
function rules(){document.getElementById('content').innerHTML="<section class='screen'><div class='pdf-card'><div><div class='eyebrow'>РЕГЛАМЕНТ</div><h2>Положение о медиаслужении</h2><p class='muted'>Цели, роли, цикл работы и стандарты публикаций.</p></div><button class='primary' onclick='window.gvbsDownloadReg&&window.gvbsDownloadReg()'>Скачать PDF</button></div></section>"}
function notify(){var perm=('Notification'in window)?Notification.permission:'unsupported';document.getElementById('content').innerHTML="<section class='screen'><div class='card'><div class='eyebrow'>PUSH</div><h2>"+(localStorage.getItem(NOTIFY)==='1'?'Уведомления включены':'Уведомления выключены')+"</h2><p class='muted'>iPhone: Safari → Поделиться → На экран Домой → открыть с иконки. Android: Chrome → разрешить уведомления.</p><div class='actions'><button class='primary' id='pushBtn'>"+(localStorage.getItem(NOTIFY)==='1'?'Отключить':'Включить')+" уведомления</button><button class='ghost' id='testBtn'>Тест</button></div></div><div class='diag'><div><strong>Permission</strong>"+perm+"</div><div><strong>Service Worker</strong>"+(('serviceWorker'in navigator)?'есть':'нет')+"</div><div><strong>Push API</strong>"+(('PushManager'in window)?'есть':'нет')+"</div></div></section>";document.getElementById('pushBtn').onclick=pushToggle;document.getElementById('testBtn').onclick=pushTest}
function profile(){var p=state.profile;document.getElementById('content').innerHTML="<section class='screen'><div class='card'><div class='profile-mini'><div class='avatar'>"+av(p)+"</div><div><h2>"+esc(p.name)+"</h2><p class='muted'>"+esc(p.role)+"</p></div></div><button class='ghost' id='logout'>Выйти</button></div></section>";document.getElementById('logout').onclick=function(){localStorage.removeItem(PROFILE);location.reload()}}
async function pushToggle(){if(localStorage.getItem(NOTIFY)==='1'){localStorage.setItem(NOTIFY,'0');shell();return}if(!('Notification'in window)){alert('Браузер не поддерживает уведомления');return}var p=await Notification.requestPermission();if(p!=='granted'){alert('Разрешение не выдано');return}localStorage.setItem(NOTIFY,'1');shell()}
async function pushTest(){try{await fetch(BACKEND_URL+'/api/push/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:state.profile.id})});alert('Тест отправлен')}catch(e){alert('Backend недоступен')}}
async function load(){if(!db)return;var r=await db.from(TABLE).select('*').order('created_at',{ascending:true});if(!r.error){state.messages=r.data||[];var c=document.getElementById('conn');if(c)c.textContent='Подключено';messages()}}
window.addEventListener('error',function(e){alertErr(e.error||e.message)});init();
})();
