import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';
const SUPABASE_URL='https://gbtmdwknkepuqbsefhto.supabase.co';
const SUPABASE_KEY='sb_publishable_4BB1LRShAX8uRQXACVN5rg_CaPtiiHz';
const BACKEND_URL='https://max-church-chat-starter-supabase.onrender.com';
const TABLE='media_chat_messages';
const BUCKET='media-chat';
const ACCESS='MEDIA2026';
const PROFILE='gvbs-v2-profile';
const NOTIFY='gvbs-notify-enabled';
const EMOJIS=['😀','😂','😊','😍','🙏','🙌','👏','❤️','💙','🔥','👍','👎','👀','🎬','📸','🎤','✨'];
const REACTIONS=['👍','👎','❤️','🙏','🔥','👀'];
const ROLES=['Руководитель','Координатор','Оператор','Фотограф','Монтажёр','Звук','Свет','Дизайн','Публикатор','Участник'];
const db=createClient(SUPABASE_URL,SUPABASE_KEY);const app=document.getElementById('app');
let state={profile:json(PROFILE,null),tab:'chat',messages:[],files:[],audio:null,rec:null,chunks:[],emoji:false,reactions:json('gvbs-v2-reactions',{})};
function json(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function esc(t){const d=document.createElement('div');d.textContent=t??'';return d.innerHTML}function vib(n=12){try{navigator.vibrate?.(n)}catch{}}function av(p){return p?.avatar?`<img src='${p.avatar}'>`:(p?.name||'U').slice(0,1).toUpperCase()}function time(v){return new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function renderLogin(){app.innerHTML=`<div class='login'><div class='login-card'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>GVBS MEDIA HUB</div><h1>Вход в чат медиаслужения</h1></div></div><p class='muted'>Закрытое рабочее пространство команды: чат, регламент, файлы, уведомления и профиль.</p><div class='form'><input class='input' id='name' placeholder='Имя'><select class='input' id='role'>${ROLES.map(r=>`<option>${r}</option>`).join('')}</select><input class='input' id='code' placeholder='Код доступа'><input id='avatar' class='fileInput' type='file' accept='image/*'><button class='ghost' id='pick'>Загрузить аватар</button><button class='primary' id='enter'>Войти</button><div class='note' id='note'>Код доступа нужен, чтобы чат не открывался посторонним.</div></div></div></div>`;let avatar='';document.getElementById('pick').onclick=()=>document.getElementById('avatar').click();document.getElementById('avatar').onchange=async()=>{const f=document.getElementById('avatar').files[0];if(!f)return;avatar=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)});document.getElementById('note').textContent='Аватар загружен'};document.getElementById('enter').onclick=()=>{const name=document.getElementById('name').value.trim();const role=document.getElementById('role').value;const code=document.getElementById('code').value.trim();if(code!==ACCESS){alert('Неверный код доступа');return}if(!name)return;state.profile={id:crypto.randomUUID(),name,role,avatar};save(PROFILE,state.profile);boot()}}
function shell(){const p=state.profile;app.innerHTML=`<div class='app'><div class='layout'><aside class='side'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>MEDIA HUB</div><h1>Медиа-служение</h1></div></div><p class='muted'>Командный чат, файлы, регламент и push-уведомления.</p><div class='profile-mini'><div class='avatar'>${av(p)}</div><div><strong>${esc(p.name)}</strong><div class='muted'>${esc(p.role)}</div></div></div><div class='metric'><div><strong>Статус</strong><br><span class='muted' id='conn'>Подключение...</span></div><div><strong>Push</strong><br><span class='muted'>${localStorage.getItem(NOTIFY)==='1'?'включены':'выключены'}</span></div></div></aside><main class='main'><header class='top'><div><h2>${title()}</h2><div class='muted'>${subtitle()}</div></div><div class='top-actions'><span class='chip'>online</span><button class='profile-btn' onclick='window.gvbsTab("profile")'><div class='avatar sm'>${av(p)}</div></button></div></header><section class='content' id='content'></section><nav class='bottom'>${nav()}</nav></main></div></div>`;drawTab()}
function title(){return{chat:'GVBS Media Hub',files:'Файлы команды',rules:'Регламент',notify:'Уведомления',profile:'Профиль'}[state.tab]||'GVBS'}function subtitle(){return{chat:'Чат медиаслужения · фото · голосовые · реакции',files:'Документы, чек-листы и материалы',rules:'Актуальное положение о медиаслужении',notify:'Push-статус и диагностика',profile:'Настройки участника'}[state.tab]||''}function nav(){return[['chat','💬','Чат'],['files','📁','Файлы'],['rules','📄','Регламент'],['notify','🔔','Push'],['profile','👤','Профиль']].map(x=>`<button class='nav ${state.tab===x[0]?'active':''}' onclick='window.gvbsTab("${x[0]}")'><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}window.gvbsTab=t=>{state.tab=t;shell()};
function drawTab(){if(state.tab==='chat')drawChat();if(state.tab==='files')drawFiles();if(state.tab==='rules')drawRules();if(state.tab==='notify')drawNotify();if(state.tab==='profile')drawProfile()}
function drawChat(){document.getElementById('content').innerHTML=`<div class='chat-screen'><div class='messages' id='msgs'></div><button class='jump hidden' id='jump'>↓</button><div class='composer'><div class='emoji-panel ${state.emoji?'open':''}' id='emoji'>${EMOJIS.map(e=>`<button>${e}</button>`).join('')}</div><div class='preview' id='preview'></div><div class='composer-row'><button class='tool' id='em'>😊</button><textarea class='input' id='txt' maxlength='3000' placeholder='Сообщение'></textarea><input id='photo' class='fileInput' type='file' accept='image/*' multiple><button class='tool' id='clip'>📎</button><button class='send' id='send'>🎤</button></div></div></div>`;bindComposer();drawMessages()}
function drawMessages(){const box=document.getElementById('msgs');if(!box)return;box.innerHTML=state.messages.map(m=>{const own=m.author_id===state.profile.id;const reacts=state.reactions[m.id]||'';return`<div class='msg ${own?'own':''}'><div class='bubble'><div class='meta'><strong>${esc(m.author_name)}</strong><span class='role'>${esc(m.author_role||'Участник')}</span><span>${time(m.created_at)}</span>${own&&!m.deleted_at?`<button class='mini-btn' data-edit='${m.id}'>✎</button><button class='mini-btn' data-del='${m.id}'>✕</button>`:''}</div>${m.deleted_at?`<div class='deleted'>Сообщение удалено</div>`:`<div class='text'>${esc(m.text||'')}</div>`}${(m.attachments||[]).length?`<div class='media'>${m.attachments.map(a=>a.kind==='audio'?`<audio controls src='${a.url}'></audio>`:`<img src='${a.url}'>`).join('')}</div>`:''}<div class='msg-actions'>${REACTIONS.map(r=>`<button class='react ${reacts===r?'active':''}' data-r='${r}' data-id='${m.id}'>${r}</button>`).join('')}</div></div></div>`}).join('');box.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{state.reactions[b.dataset.id]=state.reactions[b.dataset.id]===b.dataset.r?'':b.dataset.r;save('gvbs-v2-reactions',state.reactions);drawMessages()});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>db.from(TABLE).update({text:'',deleted_at:new Date().toISOString()}).eq('id',b.dataset.del));box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const m=state.messages.find(x=>x.id===b.dataset.edit);const next=prompt('Редактировать',m?.text||'');if(next!=null)await db.from(TABLE).update({text:next}).eq('id',b.dataset.edit)});setTimeout(()=>box.scrollTo({top:box.scrollHeight}),30)}
function bindComposer(){const t=document.getElementById('txt'),s=document.getElementById('send');document.getElementById('em').onclick=()=>{state.emoji=!state.emoji;document.getElementById('emoji').classList.toggle('open',state.emoji)};document.querySelectorAll('#emoji button').forEach(b=>b.onclick=()=>{t.value+=b.textContent;t.dispatchEvent(new Event('input'))});document.getElementById('clip').onclick=()=>document.getElementById('photo').click();document.getElementById('photo').onchange=()=>{state.files=[...document.getElementById('photo').files].filter(f=>f.type.startsWith('image/')&&f.size<=10*1024*1024).slice(0,6);preview();mode()};t.oninput=()=>{t.style.height='0px';t.style.height=Math.min(t.scrollHeight,170)+'px';mode()};t.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMsg()}};s.onclick=()=>t.value.trim()||state.files.length||state.audio?sendMsg():rec();mode()}
function preview(){document.getElementById('preview').innerHTML=[...state.files.map(f=>`<span>${esc(f.name)}</span>`),state.audio?'<span>Голосовое готово</span>':''].join('')}function mode(){const t=document.getElementById('txt'),s=document.getElementById('send');if(s)s.textContent=t.value.trim()||state.files.length||state.audio?'➤':state.rec?'⏺':'🎤'}
async function upload(){const out=[];for(const f of state.files){const path=`${Date.now()}-${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Zа-яА-Я0-9._-]/g,'_')}`;const r=await db.storage.from(BUCKET).upload(path,f,{upsert:false});if(r.error)throw r.error;out.push({kind:'image',name:f.name,url:db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl})}if(state.audio){const f=new File([state.audio],`voice-${Date.now()}.webm`,{type:'audio/webm'});const path=`${Date.now()}-${crypto.randomUUID()}-${f.name}`;const r=await db.storage.from(BUCKET).upload(path,f,{upsert:false});if(r.error)throw r.error;out.push({kind:'audio',name:f.name,url:db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl})}return out}
async function sendMsg(){const t=document.getElementById('txt');const text=t.value.trim();if(!text&&!state.files.length&&!state.audio)return;try{const attachments=await upload();await db.from(TABLE).insert({author_id:state.profile.id,author_name:state.profile.name,author_role:state.profile.role,text,attachments});state.files=[];state.audio=null;t.value='';preview();mode();vib()}catch(e){alert(e.message||'Ошибка отправки')}}async function rec(){if(state.rec){state.rec.stop();state.rec=null;mode();return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];const r=new MediaRecorder(stream);r.ondataavailable=e=>state.chunks.push(e.data);r.onstop=()=>{state.audio=new Blob(state.chunks,{type:'audio/webm'});stream.getTracks().forEach(t=>t.stop());preview();mode()};r.start();state.rec=r;mode()}
function drawFiles(){document.getElementById('content').innerHTML=`<section class='screen'><div class='grid'><div class='card'><div class='eyebrow'>ФАЙЛЫ</div><h2>Материалы команды</h2><p class='muted'>Регламенты, чек-листы, шаблоны и полезные ссылки.</p></div><div class='card'><strong>Положение о медиаслужении</strong><p class='muted'>PDF · рабочая версия · церковь «Ковчег спасения», Омск</p><div class='actions'><button class='primary' onclick='window.gvbsDownloadReg()'>Скачать PDF</button></div></div><div class='card'><strong>Чек-лист воскресного служения</strong><p class='muted'>Будет добавлен следующим этапом.</p></div></div></section>`}
function drawRules(){document.getElementById('content').innerHTML=`<section class='screen'><div class='pdf-card'><div style='display:flex;gap:14px'><div class='pdf-icon'>PDF</div><div><div class='eyebrow'>АКТУАЛЬНЫЙ ДОКУМЕНТ</div><h2>Положение о медиаслужении</h2><p class='muted'>Цели, роли, еженедельный цикл, стандарты публикаций и порядок работы.</p></div></div><div class='actions'><button class='primary' onclick='window.gvbsDownloadReg()'>Скачать PDF</button></div></div></section>`}
function drawNotify(){const perm='Notification'in window?Notification.permission:'unsupported';document.getElementById('content').innerHTML=`<section class='screen'><div class='grid'><div class='card'><div class='eyebrow'>PUSH</div><h2>${localStorage.getItem(NOTIFY)==='1'?'Уведомления включены':'Уведомления выключены'}</h2><p class='muted'>На iPhone: Safari → Поделиться → На экран Домой → открыть с иконки → включить. На Android: Chrome → разрешить уведомления.</p><div class='actions'><button class='primary' id='pushToggle'>${localStorage.getItem(NOTIFY)==='1'?'Отключить':'Включить'} уведомления</button><button class='ghost' id='pushTest'>Тест</button></div></div><div class='diag'><div><strong>HTTPS</strong>${location.protocol==='https:'?'да':'нет'}</div><div><strong>Permission</strong>${perm}</div><div><strong>Service Worker</strong>${'serviceWorker'in navigator?'есть':'нет'}</div><div><strong>Push API</strong>${'PushManager'in window?'есть':'нет'}</div></div></div></section>`;document.getElementById('pushToggle').onclick=togglePush;document.getElementById('pushTest').onclick=testPush}
function drawProfile(){const p=state.profile;document.getElementById('content').innerHTML=`<section class='screen'><div class='card'><div class='profile-mini'><div class='avatar'>${av(p)}</div><div><h2>${esc(p.name)}</h2><p class='muted'>${esc(p.role)}</p></div></div><div class='actions'><button class='ghost' onclick='localStorage.removeItem("${PROFILE}");location.reload()'>Выйти</button></div></div></section>`}
async function togglePush(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){alert('Этот браузер не поддерживает push. На iPhone установи приложение на экран Домой.');return}if(localStorage.getItem(NOTIFY)==='1'){localStorage.setItem(NOTIFY,'0');shell();return}const perm=await Notification.requestPermission();if(perm!=='granted'){alert('Разрешение не выдано');return}try{const reg=await navigator.serviceWorker.register('./sw.js?v=30');await navigator.serviceWorker.ready;const k=await fetch(BACKEND_URL+'/api/push/public-key').then(r=>r.json());if(!k.enabled)throw new Error('Backend push не настроен');const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlB64(k.publicKey)});await fetch(BACKEND_URL+'/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:state.profile.id,subscription:sub})});localStorage.setItem(NOTIFY,'1');shell()}catch(e){alert(e.message)}}function urlB64(s){const p='='.repeat((4-s.length%4)%4);const b=(s+p).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from([...atob(b)].map(c=>c.charCodeAt(0)))}async function testPush(){await fetch(BACKEND_URL+'/api/push/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:state.profile.id})});alert('Тест отправлен')}
window.gvbsDownloadReg=()=>{if(window.downloadRegulation)window.downloadRegulation();else alert('PDF-модуль загружается. Обнови страницу.')}async function load(){const r=await db.from(TABLE).select('*').order('created_at',{ascending:true});if(!r.error){state.messages=r.data||[];document.getElementById('conn')&&(document.getElementById('conn').textContent='Подключено');drawMessages()}}function boot(){shell();load();db.channel('v2-chat').on('postgres_changes',{event:'*',schema:'public',table:TABLE},load).subscribe()}
state.profile?boot():renderLogin();
