(function(){
var SUPABASE_URL='https://gbtmdwknkepuqbsefhto.supabase.co';
var SUPABASE_KEY='sb_publishable_4BB1LRShAX8uRQXACVN5rg_CaPtiiHz';
var BACKEND_URL='https://max-church-chat-starter-supabase.onrender.com';
var TABLE='media_chat_messages';
var REACTIONS_TABLE='message_reactions';
var BUCKET='media-chat';
var ACCESS='MEDIA2026';
var PROFILE='gvbs-v2-profile';
var NOTIFY='gvbs-notify-enabled';
var EMOJIS=['😀','😂','😊','😍','🙏','🙌','👏','❤️','💙','🔥','👍','👎','👀','🎬','📸','🎤','✨'];
var REACTIONS=['👍','👎','❤️','🙏','🔥','👀'];
var ROLES=['Руководитель','Координатор','Оператор','Фотограф','Монтажёр','Звук','Свет','Дизайн','Публикатор','Участник'];
var app=document.getElementById('app');
var db=null;
var state={profile:read(PROFILE,null),tab:'chat',messages:[],files:[],audio:null,rec:null,chunks:[],emoji:false,reactions:read('gvbs-v2-reactions',{}),reactionCounts:{},sharedReactions:true,stickToBottom:true,loadedOnce:false};
function read(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(t){var d=document.createElement('div');d.textContent=t||'';return d.innerHTML}
function av(p){return p&&p.avatar?"<img src='"+p.avatar+"'>":esc(((p&&p.name)||'U').slice(0,1).toUpperCase())}
function tm(v){try{return new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){return''}}
function alertErr(e){console.error(e);app.innerHTML="<div class='login'><div class='login-card'><div class='eyebrow'>GVBS MEDIA HUB</div><h1>Не удалось открыть приложение</h1><p class='muted'>Ошибка загрузки. Обнови страницу или открой в инкогнито.</p><button class='primary' onclick='location.reload()'>Обновить</button><pre class='note'>"+esc(e&&e.message?e.message:String(e))+"</pre></div></div>"}
function init(){try{if(!window.supabase||!window.supabase.createClient)throw new Error('Supabase SDK не загрузился');db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);state.profile?boot():login()}catch(e){alertErr(e)}}
function login(){app.innerHTML="<div class='login'><div class='login-card'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>GVBS MEDIA HUB</div><h1>Вход в чат медиаслужения</h1></div></div><p class='muted'>Закрытое пространство команды: чат, регламент, файлы, уведомления и профиль.</p><div class='form'><input class='input' id='name' placeholder='Имя'><select class='input' id='role'>"+ROLES.map(function(r){return'<option>'+r+'</option>'}).join('')+"</select><input class='input' id='code' placeholder='Код доступа'><input id='avatar' class='fileInput' type='file' accept='image/*'><button class='ghost' id='pick'>Загрузить аватар</button><button class='primary' id='enter'>Войти</button><div class='note' id='note'>Код доступа: MEDIA2026</div></div></div></div>";var avatar='';document.getElementById('pick').onclick=function(){document.getElementById('avatar').click()};document.getElementById('avatar').onchange=function(){var f=this.files[0];if(!f)return;var fr=new FileReader();fr.onload=function(){avatar=fr.result;document.getElementById('note').textContent='Аватар загружен'};fr.readAsDataURL(f)};document.getElementById('enter').onclick=function(){var name=document.getElementById('name').value.trim();var role=document.getElementById('role').value;var code=document.getElementById('code').value.trim();if(code!==ACCESS){alert('Неверный код доступа');return}if(!name)return;state.profile={id:crypto.randomUUID(),name:name,role:role,avatar:avatar};save(PROFILE,state.profile);boot()}}
function boot(){shell();load();db.channel('v2-chat').on('postgres_changes',{event:'*',schema:'public',table:TABLE},function(){load()}).subscribe();db.channel('v2-reactions').on('postgres_changes',{event:'*',schema:'public',table:REACTIONS_TABLE},function(){loadReactions().then(messages)}).subscribe()}
function shell(){var p=state.profile;app.innerHTML="<div class='app'><div class='layout'><aside class='side'><div class='brand'><div class='brand-mark'>G</div><div><div class='eyebrow'>MEDIA HUB</div><h1>Медиа-служение</h1></div></div><p class='muted'>Командный чат, файлы, регламент и push-уведомления.</p><div class='profile-mini'><div class='avatar'>"+av(p)+"</div><div><strong>"+esc(p.name)+"</strong><div class='muted'>"+esc(p.role)+"</div></div></div><div class='metric'><div><strong>Статус</strong><br><span class='muted' id='conn'>Подключение...</span></div><div><strong>Push</strong><br><span class='muted'>"+(localStorage.getItem(NOTIFY)==='1'?'включены':'выключены')+"</span></div><div><strong>Реакции</strong><br><span class='muted'>"+(state.sharedReactions?'общие':'локальные')+"</span></div></div></aside><main class='main'><header class='top'><div><h2>"+title()+"</h2><div class='muted'>"+sub()+"</div></div><button class='profile-btn' id='profileBtn'><div class='avatar sm'>"+av(p)+"</div></button></header><section class='content' id='content'></section><nav class='bottom'>"+nav()+"</nav></main></div></div>";document.getElementById('profileBtn').onclick=function(){state.tab='profile';shell()};Array.prototype.forEach.call(document.querySelectorAll('[data-tab]'),function(b){b.onclick=function(){state.tab=this.dataset.tab;shell()}});draw()}
function title(){return{chat:'GVBS Media Hub',files:'Файлы команды',rules:'Регламент',notify:'Уведомления',profile:'Профиль'}[state.tab]||'GVBS'}
function sub(){return{chat:'Чат медиаслужения · фото · голосовые · реакции',files:'Документы и материалы',rules:'Положение о медиаслужении',notify:'Push и диагностика',profile:'Настройки участника'}[state.tab]||''}
function nav(){return[['chat','💬','Чат'],['files','📁','Файлы'],['rules','📄','Регламент'],['notify','🔔','Push'],['profile','👤','Профиль']].map(function(x){return"<button class='nav "+(state.tab===x[0]?'active':'')+"' data-tab='"+x[0]+"'><b>"+x[1]+"</b><span>"+x[2]+"</span></button>"}).join('')}
function draw(){if(state.tab==='chat')chat();if(state.tab==='files')files();if(state.tab==='rules')rules();if(state.tab==='notify')notify();if(state.tab==='profile')profile()}
function chat(){document.getElementById('content').innerHTML="<div class='chat-screen'><div class='messages' id='msgs'></div><button class='jump hidden' id='jump'>↓</button><div class='composer'><div class='emoji-panel' id='emoji'>"+EMOJIS.map(function(e){return'<button>'+e+'</button>'}).join('')+"</div><div class='preview' id='preview'></div><div class='composer-row'><button class='tool' id='em'>😊</button><textarea class='input' id='txt' maxlength='3000' placeholder='Сообщение'></textarea><input id='photo' class='fileInput' type='file' accept='image/*' multiple><button class='tool' id='clip'>📎</button><button class='send' id='send'>🎤</button></div></div></div>";bindComposer();messages()}
function messages(){var box=document.getElementById('msgs');if(!box)return;var oldBottom=box.scrollHeight-box.scrollTop-box.clientHeight;box.innerHTML=state.messages.map(function(m){var own=m.author_id===state.profile.id;var my=state.reactions[m.id]||'';var counts=state.reactionCounts[m.id]||{};return"<div class='msg "+(own?'own':'')+"'><div class='bubble'><div class='meta'><strong>"+esc(m.author_name)+"</strong><span class='role'>"+esc(m.author_role||'Участник')+"</span><span>"+tm(m.created_at)+"</span></div>"+(m.deleted_at?"<div class='deleted'>Сообщение удалено</div>":"<div class='text'>"+esc(m.text||'')+"</div>")+media(m)+"<div class='msg-actions'>"+REACTIONS.map(function(r){var c=counts[r]||0;return"<button class='react "+(my===r?'active':'')+"' data-id='"+m.id+"' data-r='"+r+"'>"+r+(c?' '+c:'')+"</button>"}).join('')+"</div></div></div>"}).join('');Array.prototype.forEach.call(box.querySelectorAll('[data-r]'),function(b){b.onclick=function(){toggleReaction(b.dataset.id,b.dataset.r)}});box.onscroll=function(){var dist=box.scrollHeight-box.scrollTop-box.clientHeight;state.stickToBottom=dist<170;var j=document.getElementById('jump');if(j)j.classList.toggle('hidden',dist<170)};var j=document.getElementById('jump');if(j)j.onclick=function(){state.stickToBottom=true;box.scrollTo({top:box.scrollHeight,behavior:'smooth'});j.classList.add('hidden')};setTimeout(function(){if(!state.loadedOnce||state.stickToBottom||oldBottom<170){box.scrollTop=box.scrollHeight}state.loadedOnce=true},30)}
function media(m){var a=m.attachments||[];if(!a.length)return'';return"<div class='media'>"+a.map(function(x){return x.kind==='audio'?"<audio controls src='"+x.url+"'></audio>":"<img src='"+x.url+"'>"}).join('')+"</div>"}
function bindComposer(){var t=document.getElementById('txt'),s=document.getElementById('send');document.getElementById('em').onclick=function(){document.getElementById('emoji').classList.toggle('open')};Array.prototype.forEach.call(document.querySelectorAll('#emoji button'),function(b){b.onclick=function(){t.value+=b.textContent;mode()}});document.getElementById('clip').onclick=function(){document.getElementById('photo').click()};document.getElementById('photo').onchange=function(){state.files=Array.prototype.slice.call(this.files).filter(function(f){return f.type.indexOf('image/')===0&&f.size<=10485760}).slice(0,6);preview();mode()};t.oninput=function(){this.style.height='0px';this.style.height=Math.min(this.scrollHeight,170)+'px';mode()};t.onkeydown=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};s.onclick=function(){t.value.trim()||state.files.length||state.audio?send():record()};mode();preview()}
function preview(){var p=document.getElementById('preview');if(!p)return;p.innerHTML=state.files.map(function(f){return'<span>'+esc(f.name)+'</span>'}).join('')+(state.audio?'<span>Голосовое готово</span>':'')+(state.rec?'<span>Идёт запись...</span>':'')}
function mode(){var t=document.getElementById('txt'),s=document.getElementById('send');if(!s)return;var ready=(t&&t.value.trim())||state.files.length||state.audio;s.textContent=ready?'➤':state.rec?'⏺':'🎤';s.classList.toggle('recording',!!state.rec)}
async function upload(){var out=[];for(var i=0;i<state.files.length;i++){var f=state.files[i];var path=Date.now()+'-'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Zа-яА-Я0-9._-]/g,'_');var r=await db.storage.from(BUCKET).upload(path,f,{upsert:false});if(r.error)throw r.error;out.push({kind:'image',name:f.name,url:db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl})}if(state.audio){var vf=new File([state.audio],'voice-'+Date.now()+'.webm',{type:'audio/webm'});var vpath=Date.now()+'-'+crypto.randomUUID()+'-'+vf.name;var vr=await db.storage.from(BUCKET).upload(vpath,vf,{upsert:false});if(vr.error)throw vr.error;out.push({kind:'audio',name:vf.name,url:db.storage.from(BUCKET).getPublicUrl(vpath).data.publicUrl})}return out}
async function send(){var t=document.getElementById('txt');var text=t.value.trim();if(!text&&!state.files.length&&!state.audio)return;try{var attachments=await upload();var payload={author_id:state.profile.id,author_name:state.profile.name,author_role:state.profile.role,text:text,attachments:attachments};var r=await db.from(TABLE).insert(payload).select().single();if(r.error)throw r.error;sendPush(r.data||payload);state.files=[];state.audio=null;t.value='';preview();mode();state.stickToBottom=true}catch(e){alert(e.message||'Ошибка отправки')}}
async function record(){if(state.rec){state.rec.stop();state.rec=null;preview();mode();return}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){alert('Браузер не поддерживает запись звука');return}try{var stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];var rec=new MediaRecorder(stream);rec.ondataavailable=function(e){if(e.data&&e.data.size)state.chunks.push(e.data)};rec.onstop=function(){state.audio=new Blob(state.chunks,{type:'audio/webm'});stream.getTracks().forEach(function(t){t.stop()});state.rec=null;preview();mode()};rec.start();state.rec=rec;preview();mode()}catch(e){alert('Не удалось включить микрофон')}}
async function sendPush(m){var text=(m.text||'').trim();var att=m.attachments||[];var fallback=att.some(function(a){return a.kind==='audio'})?'Голосовое сообщение':att.length?'Фото':'Новое сообщение';var fd=new FormData();fd.append('authorId',state.profile.id);fd.append('authorName',state.profile.name);fd.append('text',text||fallback);try{await fetch(BACKEND_URL+'/api/messages',{method:'POST',body:fd})}catch(e){}}
async function loadReactions(){if(!state.messages.length)return;var ids=state.messages.map(function(m){return m.id}).filter(Boolean);if(!ids.length)return;try{var r=await db.from(REACTIONS_TABLE).select('*').in('message_id',ids);if(r.error)throw r.error;state.sharedReactions=true;var mine={},counts={};(r.data||[]).forEach(function(x){counts[x.message_id]=counts[x.message_id]||{};counts[x.message_id][x.emoji]=(counts[x.message_id][x.emoji]||0)+1;if(x.user_id===state.profile.id)mine[x.message_id]=x.emoji});state.reactions=mine;state.reactionCounts=counts}catch(e){state.sharedReactions=false;state.reactionCounts={}}}
async function toggleReaction(id,emoji){if(!id)return;if(!state.sharedReactions){state.reactions[id]=state.reactions[id]===emoji?'':emoji;save('gvbs-v2-reactions',state.reactions);messages();return}try{if(state.reactions[id]===emoji){await db.from(REACTIONS_TABLE).delete().eq('message_id',id).eq('user_id',state.profile.id)}else{await db.from(REACTIONS_TABLE).upsert({message_id:id,user_id:state.profile.id,emoji:emoji},{onConflict:'message_id,user_id'})}await loadReactions();messages()}catch(e){state.sharedReactions=false;state.reactions[id]=state.reactions[id]===emoji?'':emoji;save('gvbs-v2-reactions',state.reactions);messages()}}
function files(){document.getElementById('content').innerHTML="<section class='screen'><div class='grid'><div class='card'><div class='eyebrow'>ФАЙЛЫ</div><h2>Материалы команды</h2><p class='muted'>Регламенты, чек-листы, шаблоны и ссылки.</p></div><div class='card'><strong>Положение о медиаслужении</strong><p class='muted'>PDF · рабочая версия</p><button class='primary' onclick='window.gvbsDownloadReg&&window.gvbsDownloadReg()'>Скачать PDF</button></div></div></section>"}
function rules(){document.getElementById('content').innerHTML="<section class='screen'><div class='pdf-card'><div><div class='eyebrow'>РЕГЛАМЕНТ</div><h2>Положение о медиаслужении</h2><p class='muted'>Цели, роли, цикл работы и стандарты публикаций.</p></div><button class='primary' onclick='window.gvbsDownloadReg&&window.gvbsDownloadReg()'>Скачать PDF</button></div></section>"}
function notify(){var perm=('Notification'in window)?Notification.permission:'unsupported';document.getElementById('content').innerHTML="<section class='screen'><div class='card'><div class='eyebrow'>PUSH</div><h2>"+(localStorage.getItem(NOTIFY)==='1'?'Уведомления включены':'Уведомления выключены')+"</h2><p class='muted'>iPhone: Safari → Поделиться → На экран Домой → открыть с иконки. Android: Chrome → разрешить уведомления.</p><div class='actions'><button class='primary' id='pushBtn'>"+(localStorage.getItem(NOTIFY)==='1'?'Отключить':'Включить')+" уведомления</button><button class='ghost' id='testBtn'>Тест</button></div></div><div class='diag'><div><strong>Permission</strong>"+perm+"</div><div><strong>Service Worker</strong>"+(('serviceWorker'in navigator)?'есть':'нет')+"</div><div><strong>Push API</strong>"+(('PushManager'in window)?'есть':'нет')+"</div><div><strong>Backend</strong><span id='be'>проверка</span></div></div></section>";document.getElementById('pushBtn').onclick=pushToggle;document.getElementById('testBtn').onclick=pushTest;fetch(BACKEND_URL+'/api/health').then(function(r){return r.json()}).then(function(d){var el=document.getElementById('be');if(el)el.textContent=d.ok?'online':'ошибка'}).catch(function(){var el=document.getElementById('be');if(el)el.textContent='offline'})}
function profile(){var p=state.profile;document.getElementById('content').innerHTML="<section class='screen'><div class='card'><div class='profile-mini'><div class='avatar'>"+av(p)+"</div><div><h2>"+esc(p.name)+"</h2><p class='muted'>"+esc(p.role)+"</p></div></div><button class='ghost' id='logout'>Выйти</button></div></section>";document.getElementById('logout').onclick=function(){localStorage.removeItem(PROFILE);location.reload()}}
async function pushToggle(){if(localStorage.getItem(NOTIFY)==='1'){try{var reg=await navigator.serviceWorker.ready;var sub=await reg.pushManager.getSubscription();if(sub){await fetch(BACKEND_URL+'/api/push/unsubscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe()}}catch(e){}localStorage.setItem(NOTIFY,'0');shell();return}if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){alert('Браузер не поддерживает push. На iPhone установи сайт на экран Домой.');return}var p=await Notification.requestPermission();if(p!=='granted'){alert('Разрешение не выдано');return}try{var reg2=await navigator.serviceWorker.register('./sw.js?v=32');await navigator.serviceWorker.ready;var key=await fetch(BACKEND_URL+'/api/push/public-key').then(function(r){return r.json()});if(!key.enabled||!key.publicKey)throw new Error('Backend push не настроен');var sub2=await reg2.pushManager.getSubscription();if(!sub2)sub2=await reg2.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlB64(key.publicKey)});await fetch(BACKEND_URL+'/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:state.profile.id,subscription:sub2})});localStorage.setItem(NOTIFY,'1');shell()}catch(e){alert(e.message||'Не удалось включить уведомления')}}
function urlB64(s){var p='='.repeat((4-s.length%4)%4);var b=(s+p).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(Array.prototype.map.call(atob(b),function(c){return c.charCodeAt(0)}))}
async function pushTest(){try{await fetch(BACKEND_URL+'/api/push/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:state.profile.id})});alert('Тест отправлен')}catch(e){alert('Backend недоступен')}}
async function load(){if(!db)return;var r=await db.from(TABLE).select('*').order('created_at',{ascending:true});if(!r.error){state.messages=r.data||[];await loadReactions();var c=document.getElementById('conn');if(c)c.textContent='Подключено';messages()}}
window.addEventListener('error',function(e){alertErr(e.error||e.message)});init();
})();
